{% set version = '0.6-0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-sf
  version: {{ version|replace("-", "_") }}

source:
  fn: sf_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/sf_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/sf/sf_{{ version }}.tar.gz
  sha256: 532692a5850e6c9ba97e1465060eb3875e727a33abb3fdb48897ee7e6585cf3c

build:
  number: 0
  skip: true  # [win]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-dbi >=0.5
    - r-rcpp
    - r-classint
    - r-magrittr
    - r-pillar
    - r-units >=0.4_6
    - posix                # [win]
    - {{native}}toolchain  # [win]
    - gcc                  # [not win]
    - r-rgdal

  run:
    - r-base
    - r-dbi >=0.5
    - r-rcpp
    - r-magrittr
    - r-units >=0.4
    - libgcc  # [not win]
    - r-rgdal

test:
  commands:
    - $R -e "library('sf')"  # [not win]
    - "\"%R%\" -e \"library('sf')\""  # [win]

about:
  home: https://github.com/edzer/sfr/
  license: GPL-2
  summary: |
    Support for simple features, a standardized way to encode spatial vector data.
    Binds to GDAL for reading and writing data, to GEOS for geometrical operations, and to Proj.4
    for projection conversions and datum transformations.
  license_family: GPL2

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
