{% set version = "0.8-0" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-sf
  version: {{ version|replace("-", "_") }}

source:
  url:  # [not win]
    - https://cran.r-project.org/src/contrib/sf_{{ version }}.tar.gz  # [not win]
    - https://cran.r-project.org/src/contrib/Archive/sf/sf_{{ version }}.tar.gz  # [not win]
  sha256: 8ee354f70b073bce124f2c138ebd2748936f890a7b4c380075c189cf36c0be15  # [not win]
  url: https://cran.r-project.org/bin/windows/contrib/{{ r_base[0:3] }}/sf_{{ version }}.zip  # [win]
  {% if r_base[0:3] == '3.5' %}
  sha256: 57968aeffe3ace0d35351ca6a3ad701738b142367fb8c339727b3b286980c360  # [win]
  {% else %}
  sha256: f220e738f82c2a1734704ca7d8efbcc9abb0d444dabf69f7a1868708e69aa378  # [win]  
  {% endif %}
build:
  number: 0
  merge_build_host: True  # [win]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}       # [unix]
    - {{ compiler('cxx') }}     # [unix]
    - {{ compiler('m2w64_c') }}       # [win]
    - {{ compiler('m2w64_cxx') }}     # [win]
    - posix    # [win]
    - pkg-config
  host:
    - r-base
    - r-dbi >=0.8
    - r-rcpp
    - r-classint
    - r-magrittr
    - r-units >=0.6_0
    - libgdal  # [not win]
    - proj4  # [not win]
  run:
    - r-base
    - r-dbi >=0.8
    - r-rcpp
    - r-classint >=0.2_1
    - r-magrittr
    - r-units >=0.6_0
    - libgdal  # [not win]
    - proj4  # [not win]

test:
  commands:
    - $R -e "library('sf')"  # [not win]
    - R -e \"library('sf')\"  # [win]

about:
  home: https://github.com/r-spatial/sf/
  license: GPL-2.0 | MIT
  license_file: LICENSE
  summary: Support for simple features, a standardized way to encode spatial vector data. Binds
    to 'GDAL' for reading and writing data, to 'GEOS' for geometrical operations, and
    to 'PROJ' for projection conversions and datum transformations.
  license_family: GPL2

extra:
  recipe-maintainers:
    - conda-forge/r
    - mingwandroid
