{% set version = "0.8-1" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-sf
  version: {{ version|replace("-", "_") }}

source:
  url:  # [not win]
    - https://cran.r-project.org/src/contrib/sf_{{ version }}.tar.gz  # [not win]
    - https://cran.r-project.org/src/contrib/Archive/sf/sf_{{ version }}.tar.gz  # [not win]
  sha256: a9eb53f7b5d051e6a0dc86d07f7b8b760829c9c9c0ec268b1eecde50c9d99e9f  # [not win]
  url: https://cran.r-project.org/bin/windows/contrib/{{ r_base[0:3] }}/sf_{{ version }}.zip  # [win]
  {% if r_base[0:3] == '3.5' %}
  sha256: b9a48b06aed4a67388eb80c77945392c6d2396c5585ee609a6f73deefaafc67d  # [win]
  {% else %}
  sha256: 8877c60d5973d988604b45789d3373605313d3df16d0343d62dc5466183c5b71  # [win]  
  {% endif %}
build:
  number: 1
  merge_build_host: True  # [win]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}       # [unix]
    - {{ compiler('cxx') }}     # [unix]
    - {{ compiler('m2w64_c') }}       # [win]
    - {{ compiler('m2w64_cxx') }}     # [win]
    - posix    # [win]
    - pkg-config
  host:
    - r-base
    - r-dbi >=0.8
    - r-rcpp >=0.12.18
    - r-classint >=0.4_1
    - r-magrittr
    - r-units >=0.6_0
    - libgdal  # [not win]
    - proj  # [not win]
  run:
    - r-base
    - r-dbi >=0.8
    - r-classint >=0.4_1
    - r-magrittr
    - r-units >=0.6_0
    - libgdal  # [not win]
    - proj  # [not win]

test:
  commands:
    - $R -e "library('sf')"  # [not win]
    - R -e \"library('sf')\"  # [win]

about:
  home: https://github.com/r-spatial/sf/
  license: GPL-2.0 | MIT
  license_file: LICENSE
  summary: Support for simple features, a standardized way to encode spatial vector data. Binds
    to 'GDAL' for reading and writing data, to 'GEOS' for geometrical operations, and
    to 'PROJ' for projection conversions and datum transformations.
  license_family: GPL2

extra:
  recipe-maintainers:
    - conda-forge/r
    - mingwandroid
